# Generated by Django 5.2.7 on 2025-10-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('transaction_date', models.DateField()),
            ],
        ),
    ]
