# Generated by Django 5.2.7 on 2025-10-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
